config/routes.rb
HeApp::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "homes/show"

  root to: 'pages#home'

  resources :home, only: [:index]
  resources :categories, only: [:index, :show]
  resources :projects, only: [:index, :show]
  resources :users, only: [:new, :show, :inbox]
  resources :comments, only: [:create]
  resources :user_projects, only: [:show]
  resources :images, only: [:create]
  resources :messages, only: [:create]
  resources :conversations, only: [:create]
  
  put '/update_new_message/:id', to: "conversations#update_new_message", as: :update_new_message
  get "/about", to: 'pages#about'
  get "/users/:id/inbox", to: 'users#inbox'

  delete 'logout' => 'sessions#destroy'
  get :send_project_mail, to: 'projects#send_project_mail', as: :send_project_mail

  get '/auth/:provider/callback', to: 'sessions#create'

  post 'favourited/:user_project_id', to: 'user_projects#favourited', as: 'favourited'
  get 'favourited/:user_project_id' => 'user_projects#favourited'

  post 'completed/:user_project_id', to: 'user_projects#completed', as: 'completed'
  get 'completed/:user_project_id' => 'user_projects#completed'

  resources :users do
    resources :comments
  end

  get '/users/:user_id/comments/:id' => 'comments#show'
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :projects

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :project
	belongs_to :commentable, polymorphic: true
	
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

	belongs_to :user
	has_many :messages, dependent: :destroy
	
	accepts_nested_attributes_for :messages
	
end

app/models/image.rb
class Image < ActiveRecord::Base

	belongs_to :user
	belongs_to :project
	has_many :comments, as: :commentable

	mount_uploader :original, ImageUploader

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

	belongs_to :project
	has_many :comments, as: :commentable

end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :conversation
	belongs_to :user

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :ingredients
	has_many :steps
	has_many :images
	has_many :users, through: :user_projects
	has_many :user_projects
	has_many :comments, as: :commentable
  has_one :video
	belongs_to :category
	
	ratyrate_rateable 'overall'

	scope :search, -> (title) { where("title like ?", "%" + title + "%") }

  # scope :search, -> (title) { where("title like %?%", title) }


	def youtube_url
    youtube_id = self.video.split("=").last
    "//www.youtube.com/embed/#{youtube_id}"
  end


	def get_all_comments
		all_comments = []

		project_comments = self.comments

		project_comments.includes(:user).each do |com|
			all_comments << com
		end

		# self.ingredients.includes(:comments)

		self.ingredients.each do |ing|
			ing.comments.each do |com|
				all_comments << com
			end
		end	

		# self.steps.includes(:comments)

		self.steps.each do |step|
			step.comments.each do |com|
				all_comments << com
			end
		end

		self.video.comments.each do |com|
			all_comments << com
		end

		return all_comments

	end

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/step.rb
class Step < ActiveRecord::Base

	belongs_to :project
	has_many :comments, as: :commentable

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :facebook_id, uniqueness: true

	# has_many :comments, as: :commentable
	has_many :comments
	has_many :images
	has_many :projects, through: :user_projects
	has_many :user_projects

  # Use for read-only activities only ;)
  has_many :unique_projects, -> { distinct }, through: :user_projects, source: :project, class_name: 'Project'

	has_many :messages
	has_many :conversations


	ratyrate_rater

  #Do not delete
  # mount_uploader :avatar, AvatarUploader

end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
	belongs_to :user
	belongs_to :project

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :project
  has_many :comments, as: :commentable
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
 <!-- REMOVE -->
<%# Rails flash messages styled for Zurb Foundation %>
<%# flash.each do |name, msg| %>
  <%# if msg.is_a?(String) %>
    <!-- <div data-alert class="alert-box round <%#= name.to_s == 'notice' ? 'success' : 'alert' %>"> -->
      <%#= content_tag :div, msg %>
      <!-- <a href="#" class="close">&times;</a> -->
    <!-- </div> -->
  <%# end %>
<%# end %>

app/views/layouts/_navigation.html.erb
<div class='fixed'>
  <nav class='top-bar center' data-topbar>
    <ul class="title-area left">
      <li class="name">
        <%= link_to image_tag("logo_small.png"), "/" %>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
    <section class = 'top-bar-section'>
      <ul>
        <li>
          <%= link_to "Categories", categories_path() %>
        </li>
        <li>
          <%= link_to "Popular Projects", "/projects" %>
        </li>
        <li>
          <%= link_to "About", "/about" %>
        </li>
      </ul>
    </section>
    <%= render 'pages/login' %>
    <%= render 'layouts/search' %>  
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_search.html.erb
<div class = 'search-box right'>
  <%= form_tag(projects_path, method: "get") do %>
    <%= text_field_tag :title, params[:title], placeholder: "Search by Project Title", width: "200px" %>
    <!-- TODO: handle consecutive words that don't match exactly to project title< -->
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homesteader's Notebook</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <link href='http://fonts.googleapis.com/css?family=Arvo|Architects+Daughter' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.slick/1.5.6/slick.css"/>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.slick/1.5.6/slick-theme.css"/>
    <%= csrf_meta_tags %>
    <% if current_user %>
    <script>APP = {userAvatar: "<%= current_user.avatar %>", userName: "<%= current_user.full_name %>"}</script>
    <% end %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  <script src="//cdn.jsdelivr.net/jquery.slick/1.5.6/slick.min.js"></script>
  </body>
</html

app/views/pages/_login.html.erb
<% if current_user %> 
  <div class='right user-panel logged-in'>
    <%= link_to image_tag(current_user.avatar, class: "avatar"), user_path(current_user.id) %>
    <p>
      <span>
      <%= link_to current_user.full_name, user_path(current_user.id), :id => "current-user-name" %>
      <% if  num_new_messages > 0  %>
        <%= link_to "/users/#{current_user.id}/inbox" do %>
            <%= image_tag("/svg/mail3white.svg", :width => "25px", id: "inbox-icon") %>
            <span id="inbox-count">
              <%= num_new_messages %>
            </span>
        <% end %>
      <% else %>
        <%= link_to "/users/#{current_user.id}/inbox" do %>
          <%= image_tag("/svg/mail3white.svg", :width => "25px", id: "inbox-icon") %>
        <% end %>      
      <% end %>
      </span>
      <br />

      <%= link_to 'My Projects ', user_path(current_user.id) %> |
      <%= link_to " Log out", logout_path, method: "delete" %>
    </p>
  </div>
<% else %> 
  <div class='right user-panel'>
          <!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->
    <a href ="/auth/facebook" class = 'button radius'>Login with Facebook</a>
    <!-- <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
    </fb:login-button> -->
  </div>
<% end %>

app/views/pages/_popular.html.erb
<% @popular.each do |pop| %>
  <div class="category" data-equalizer-watch>
    <img src = <%= pop.image %> />
    <h4><%= link_to pop.name, category_path(pop) %></h4>
    <p><%= pop.description %></p>
  </div>
<% end %> 

app/views/pages/_showcased.html.erb
<div class='carousel' data-slick> 
  <div>
    <%= image_tag("project_gallery/wheatgrass-5_carousel.jpg") %>
    <%= link_to project_path(8) do %>
      <div class="carousel-project">
        Grow your own wheatgrass &raquo;
      </div>
    <% end %>
    <div class='carousel-blurb'>
      <p>Start your own <br />urban homesteading project</p>
    </div>
  </div>>
  <div>
    <%= image_tag("project_gallery/sprouts-3_carousel.jpg") %>
    <%= link_to project_path(6) do %>
      <div class="carousel-project">
        Home-farm some sprouts &raquo;
      </div>
    <% end %>    
    <div class='carousel-blurb'>
      <p>Get advice from experts</p>
    </div>
  </div>
  <div>
    <%= image_tag("project_gallery/mozzarella-5_carousel.jpg") %>
    <%= link_to project_path(5) do %>
      <div class="carousel-project">
        Enjoy home-made mozzarella &raquo;
      </div>
    <% end %>
    <div class='carousel-blurb'>
      <p>Learn what it will take to finish the job</p>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="section">
  <div id='map'></div>
	<div class="row">
		<div class="large-6 columns">
			<h3><a href="http://www.homesteadersemporium.com">Homesteader's Emporium's</a> Mission</h3>
			<h5>We offer accessible, quality supplies for self-sufficiency, especially those that would otherwise be difficult or inconvenient to source. We offer a continuum of learning options, creating consistently awesome introductory content while tapping into a network of specialists to help people take their skills to higher levels. We forge alliances with grassroots organizations that promote self-sufficiency and sustainability through education.</h5>
			<h3><a href="http://www.homesteadersemporium.com">Homesteader's Emporium's</a> Vision</h3>
			<h5>Our vision is to bring self-sufficiency into the mainstream. We envision a world in which the way things are made is alive in the public's consciousness. We see a greater connection between ourselves, our neighbours, and the products we consume, and from that connection a society of greater understanding, dialogue, and sustainability. We don't imagine that every family will have it's own small farm, but we do imagine that every person will have a friend that is a farmer, and every child will grow up with a basic understanding of where food comes from. Let's get there together!</h5>
		</div>
		<div class="panel large-6 columns">
				<div class="large-6 columns">
					<h1>Store hours:</h1>
					<h4>645 East Hastings Street, Vancouver, BC</h4>
					<table>
						<tbody>
							<tr>
								<td>M Tu Th F Sa:</td>
								<td>11am-6pm</td>
							</tr>
							<tr>
								<td>W:</td>
								<td>11am-7pm</td>
							</tr>
							<tr>
								<td>Su:</td>
								<td>11am-5pm</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="large-6 columns">
					<h1>Stay in touch:</h1>
					<table>
						<tbody>
							<tr>
								<td>Website:</td>
								<td><a href="http://www.homesteadersemporium.com">homesteadersemporium.com</a></td>
							</tr>
							<tr>
								<td>Facebook:</td>
								<td><a href="http://www.facebook.com/homesteadersemporium">homesteadersemporium</a></td>
							</tr>
							<tr>
								<td>Twitter:</td>
								<td><a href="https://twitter.com/homesteadersemp">@homesteaderemp</a></td>
							</tr>
							<tr>
								<td>Instagram:</td>
								<td><a href="https://instagram.com/homesteadersemporium">homesteadersemporium</a></td>
							</tr>
							<tr>
								<td>Phone:</td>
								<td>604-568-7675</td>
							</tr>
							<tr>
								<td>Newsletter:</td>
								<td><a href="http://homesteadersemporium.us4.list-manage1.com/subscribe?u=3d31ac47cf2929ccf5da89691&id=6728f38933" class="button" target="_blank">Subscribe</a></td>
							</tr>
						</tbody>
					</table>		
				</div>
			</div>
		</div>
	</div>	 	
</div>


<script>
		  // initialize the map
	$(function($){
   var map = L.map('map').setView([49.264676, -123.049826], 12);
   var marker = L.marker([49.264676, -123.049826]).addTo(map);


    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
        maxZoom: 19,
    }).addTo(map);
  })
</script>		

app/views/pages/home.html.erb
<div class="row">
  <div class="large-12 columns carousel-wrapper" >
    <%= render 'pages/showcased' %>
  </div>
</div>
<div class="row data-equalizer">
  <div class="large-12 columns text-center popular-holder">
    <div class="popular-categories-wrapper">
      <h3 class="popular-categories">Popular Categories</h3>
    </div>
    <%= render 'pages/popular' %>
  </div>
</div>
<div class="row">
  <div class='categories'>
    <h3>All Categories:</h3>
    <% @categories.in_groups(3, false) do |group| %>
      <div class="large-4 columns">
        <ul>
          <% group.each do |category| %>
            <li><%= link_to category.name, category_path(category) %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>